name: mysqldump-acceptance-testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: apt update
      run: sudo apt-get update
      
    - name: set root password
      run: sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password sha256'
      
    - name: set root password again
      run: sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password sha256'

    - name: install mysql
      run: sudo apt-get install mysql-server -y
      
    - name: start mysql
      run: sudo /etc/init.d/mysql start
      
    - name: ps mysql
      run: ps -fea | grep mysql
      
    - name: create demoschema
      run: echo "create database demo" | mysql -psha256

    - name: ls
      run: ls -l
